# Generated by Django 4.1.5 on 2023-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='width and height for image must be 640px * 360px', upload_to='static/image/aboutus', verbose_name='image background')),
                ('header', models.CharField(max_length=200, verbose_name='header')),
                ('paragraph', models.TextField(verbose_name='paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='width and height for image must be 1920px * 1227px', upload_to='static/image/aboutus', verbose_name='image background')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
