# Generated by Django 4.1.1 on 2023-01-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='width and height for image must be 1920px * 1227px', upload_to='static/image/aboutus', verbose_name='image background')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(help_text='width and height for image must be 640px * 360px', upload_to='static/image/aboutus', verbose_name='image background'),
        ),
    ]
