# Generated by Django 4.1.5 on 2023-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='send date')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=254, null=True, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_facebook', models.BooleanField(verbose_name='show Facebook')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='facebook line')),
                ('show_twitter', models.BooleanField(verbose_name='show twitter')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='twitter line')),
                ('show_dribbble', models.BooleanField(verbose_name='show dribbble')),
                ('dribbble_link', models.URLField(blank=True, null=True, verbose_name='dribbble line')),
                ('show_behance', models.BooleanField(verbose_name='show behance')),
                ('behance_link', models.URLField(blank=True, null=True, verbose_name='behance line')),
                ('show_pinterest', models.BooleanField(verbose_name='show pinterest')),
                ('pinterest_link', models.URLField(blank=True, null=True, verbose_name='pinterest line')),
                ('show_google_plus', models.BooleanField(verbose_name='show google-plus')),
                ('google_plus_link', models.URLField(blank=True, null=True, verbose_name='google-plus line')),
                ('show_lindedin', models.BooleanField(verbose_name='show linkedin')),
                ('lindedin_link', models.URLField(blank=True, null=True, verbose_name='linkedin line')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('latitude', models.FloatField(help_text='go to google map and get latitude of your company loacation ex. 25.90009', verbose_name='latitude of company location')),
                ('longitude', models.FloatField(help_text='go to google map and get longitude of your company loacation ex. 25.90009', verbose_name='longitude of company location')),
            ],
        ),
    ]
