# Generated by Django 4.1.1 on 2023-01-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_facebook', models.BooleanField(verbose_name='show Facebook')),
                ('facebook_link', models.URLField(null=True, verbose_name='facebook line')),
                ('show_twitter', models.BooleanField(verbose_name='show twitter')),
                ('twitter_link', models.URLField(null=True, verbose_name='twitter line')),
                ('show_dribbble', models.BooleanField(verbose_name='show dribbble')),
                ('dribbble_link', models.URLField(null=True, verbose_name='dribbble line')),
                ('show_behance', models.BooleanField(verbose_name='show behance')),
                ('behance_link', models.URLField(null=True, verbose_name='behance line')),
                ('show_pinterest', models.BooleanField(verbose_name='show pinterest')),
                ('pinterest_link', models.URLField(null=True, verbose_name='pinterest line')),
                ('show_google_plus', models.BooleanField(verbose_name='show google-plus')),
                ('google_plus_link', models.URLField(null=True, verbose_name='google-plus line')),
                ('show_lindedin', models.BooleanField(verbose_name='show linkedin')),
                ('lindedin_link', models.URLField(null=True, verbose_name='linkedin line')),
            ],
        ),
    ]
