# Generated by Django 4.1.1 on 2023-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='send date')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=254, null=True, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.AlterField(
            model_name='followus',
            name='behance_link',
            field=models.URLField(blank=True, null=True, verbose_name='behance line'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='dribbble_link',
            field=models.URLField(blank=True, null=True, verbose_name='dribbble line'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='facebook line'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='google_plus_link',
            field=models.URLField(blank=True, null=True, verbose_name='google-plus line'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='lindedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin line'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='pinterest_link',
            field=models.URLField(blank=True, null=True, verbose_name='pinterest line'),
        ),
        migrations.AlterField(
            model_name='followus',
            name='twitter_link',
            field=models.URLField(blank=True, null=True, verbose_name='twitter line'),
        ),
    ]
