# Generated by Django 4.1.1 on 2023-01-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0002_contactus_alter_followus_behance_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('latitude', models.FloatField(help_text='go to google map and get latitude of your company loacation ex. 25.90009', verbose_name='latitude of company location')),
                ('longitude', models.FloatField(help_text='go to google map and get longitude of your company loacation ex. 25.90009', verbose_name='longitude of company location')),
            ],
        ),
    ]
