# Generated by Django 4.1.5 on 2023-03-16 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_header', models.CharField(max_length=400)),
                ('address', models.TextField(max_length=400)),
                ('email_header', models.CharField(max_length=400)),
                ('email1', models.EmailField(max_length=254, verbose_name='email')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email2')),
                ('phone_header', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=200)),
                ('phone2', models.CharField(blank=True, max_length=200, null=True)),
                ('text_under_line', models.CharField(max_length=200, verbose_name='text copy right')),
            ],
            options={
                'verbose_name_plural': '13. Footer',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200)),
                ('menu1', models.CharField(max_length=200)),
                ('menu2', models.CharField(max_length=200)),
                ('menu3', models.CharField(max_length=200)),
                ('menu4', models.CharField(max_length=200)),
                ('menu5', models.CharField(max_length=200)),
                ('menu6', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '01. Header (Menu)',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='logo must be width 113 px and height 41 px.', upload_to='static/image/logo', verbose_name='logo')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '11. Our Latest News',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.CharField(max_length=200)),
                ('text1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NumbersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '05. Section Numbers',
            },
        ),
        migrations.CreateModel(
            name='Partherns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('text_description', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': '12. Our Best Partherns',
            },
        ),
        migrations.CreateModel(
            name='PorfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': '071. Our Latest Portfolio Item',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=200, verbose_name='name')),
                ('paragraph', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': '07. Our Latest Portfolio',
            },
        ),
        migrations.CreateModel(
            name='SectionFiveOurTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': '09. Our Team Members',
            },
        ),
        migrations.CreateModel(
            name='SectionFourProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_background', models.ImageField(upload_to='static/image', verbose_name='image')),
                ('name_section', models.CharField(max_length=200, verbose_name='name section')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': '08. We Are Professional',
            },
        ),
        migrations.CreateModel(
            name='SectionSixCustomersSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_background', models.ImageField(upload_to='static/image', verbose_name='image background section')),
                ('header', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '10. What Our Customers Say',
            },
        ),
        migrations.CreateModel(
            name='SectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': '06. Section Our Best solutions',
            },
        ),
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/home', verbose_name='image_slide')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': '04. Section (We are Creative)',
            },
        ),
        migrations.CreateModel(
            name='SectionUnderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('header_section', models.CharField(max_length=200)),
                ('paragraph_section', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': '03. Section Under Slider (Best Sulotions)',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slide', models.ImageField(upload_to='static/image/slider', verbose_name='image_slide')),
                ('text_header_slide', models.CharField(max_length=200)),
                ('text2_slide', models.CharField(max_length=200)),
                ('text3_slide', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '02. Sliders',
            },
        ),
        migrations.CreateModel(
            name='SectionUnderSliderIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectionunderslider')),
            ],
        ),
        migrations.CreateModel(
            name='SectionThreeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Go to the https://fontawesome.com/search website and search for the name of the icon and put it in this field for example fa-user', max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
                ('section_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectionthree')),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image', verbose_name='image of team')),
                ('text_description', models.CharField(max_length=2000)),
                ('user_name', models.CharField(max_length=50, verbose_name='name of team')),
                ('department', models.CharField(max_length=50, verbose_name='department')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectionfiveourteams')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('precent', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='precent')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectiontwo')),
            ],
        ),
        migrations.CreateModel(
            name='porfolioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image', verbose_name='image')),
                ('text_description', models.TextField(max_length=2000)),
                ('porfolioItem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.porfolioitem')),
            ],
            options={
                'verbose_name_plural': '07. Our Latest Portfolio',
            },
        ),
        migrations.CreateModel(
            name='ParthernsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='static/parthers', verbose_name='image')),
                ('parthers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.partherns')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/news', verbose_name='news image')),
                ('date', models.DateField()),
                ('Header_paragraph', models.CharField(max_length=200)),
                ('text_description', models.TextField(max_length=2000)),
                ('news_section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.newssection')),
            ],
        ),
        migrations.CreateModel(
            name='CustomersSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_icon', models.ImageField(upload_to='static/image', verbose_name='customer icon')),
                ('paragraph', models.CharField(max_length=2000)),
                ('customer_name', models.CharField(max_length=2000)),
                ('customer_name2', models.CharField(max_length=2000)),
                ('customer_say', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectionsixcustomerssay')),
            ],
        ),
    ]
