# Generated by Django 4.1.1 on 2023-01-18 20:24

import builtins
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=builtins.max)),
                ('email1', models.EmailField(max_length=254, verbose_name='email')),
                ('email2', models.EmailField(default='', max_length=254, verbose_name='email2')),
                ('phone', models.CharField(max_length=200)),
                ('phone2', models.CharField(default='', max_length=200)),
                ('text_under_line', models.CharField(max_length=200, verbose_name='text copy right')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200)),
                ('menu1', models.CharField(max_length=200)),
                ('menu2', models.CharField(max_length=200)),
                ('menu3', models.CharField(max_length=200)),
                ('menu4', models.CharField(max_length=200)),
                ('menu5', models.CharField(max_length=200)),
                ('menu6', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/news', verbose_name='image')),
                ('date', models.DateField()),
                ('Header_paragraph', models.CharField(max_length=200)),
                ('text_description', models.TextField(max_length=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.CharField(max_length=200)),
                ('text1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NumbersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partherns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('text_description', models.TextField(max_length=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='ParthernsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(height_field=95, upload_to='parthers', verbose_name='image', width_field=135)),
            ],
        ),
        migrations.CreateModel(
            name='porfolioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='image')),
                ('text_description', models.TextField(max_length=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=200, verbose_name='name')),
                ('paragraph', models.TextField(max_length=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=2000)),
                ('precent', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='precent')),
            ],
        ),
        migrations.CreateModel(
            name='SectionFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_background', models.ImageField(upload_to='image', verbose_name='image')),
                ('name_section', models.CharField(max_length=200, verbose_name='name')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', verbose_name='image')),
                ('text_description', models.TextField(max_length=builtins.max)),
            ],
        ),
        migrations.CreateModel(
            name='SectionSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_background', models.ImageField(upload_to='image', verbose_name='image')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionThreeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/home', verbose_name='image_slide')),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionUnderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('header_section', models.CharField(max_length=200)),
                ('paragraph_section', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SectionUnderSliderIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slide', models.ImageField(upload_to='static/image/slider', verbose_name='image_slide')),
                ('text_header_slide', models.CharField(max_length=200)),
                ('text2_slide', models.CharField(max_length=200)),
                ('text3_slide', models.CharField(max_length=200)),
            ],
        ),
    ]
