# Generated by Django 4.1.1 on 2023-01-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_portfolio_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfolioitem',
            name='image',
        ),
        migrations.AddField(
            model_name='porfoliodetail',
            name='porfolioItem',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='content.porfolioitem'),
            preserve_default=False,
        ),
    ]
