# Generated by Django 4.1.1 on 2023-01-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_porfolioitem_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionFour',
            new_name='SectionFourProfessional',
        ),
        migrations.AlterField(
            model_name='porfoliodetail',
            name='image',
            field=models.ImageField(upload_to='static/image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='porfoliodetail',
            name='text_description',
            field=models.TextField(max_length=2000),
        ),
    ]
