# Generated by Django 4.1.1 on 2023-01-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_sectionfour_sectionfourprofessional_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionFive',
            new_name='SectionFiveOurTeams',
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='team',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='content.sectionfiveourteams'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionfourprofessional',
            name='name_section',
            field=models.CharField(max_length=200, verbose_name='name section'),
        ),
    ]
