# Generated by Django 4.1.1 on 2023-01-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_sectionimage_department_sectionimage_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSixCustomersSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_background', models.ImageField(upload_to='image', verbose_name='image')),
                ('header', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SectionSix',
        ),
        migrations.AlterField(
            model_name='sectionfiveourteams',
            name='paragraph',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='image',
            field=models.ImageField(upload_to='static/image', verbose_name='image of team'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='text_description',
            field=models.CharField(max_length=2000),
        ),
    ]
