# Generated by Django 4.1.1 on 2023-01-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_sectionsixcustomerssay_delete_sectionsix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_icon', models.ImageField(upload_to='image', verbose_name='customer icon')),
                ('paragraph', models.CharField(max_length=2000)),
                ('customer_name', models.CharField(max_length=2000)),
                ('customer_name2', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='sectionsixcustomerssay',
            name='image_background',
            field=models.ImageField(upload_to='image', verbose_name='image background section'),
        ),
        migrations.AddField(
            model_name='sectionsixcustomerssay',
            name='customer_say',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='content.customerssay'),
            preserve_default=False,
        ),
    ]
