# Generated by Django 4.1.1 on 2023-01-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_customerssay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionsixcustomerssay',
            name='customer_say',
        ),
        migrations.AddField(
            model_name='customerssay',
            name='customer_say',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='content.sectionsixcustomerssay'),
            preserve_default=False,
        ),
    ]
