# Generated by Django 4.1.1 on 2023-01-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_sectionsixcustomerssay_customer_say_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='news_section',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='content.newssection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerssay',
            name='customer_icon',
            field=models.ImageField(upload_to='static/image', verbose_name='customer icon'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='static/image/news', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='parthernsimage',
            name='icon',
            field=models.ImageField(height_field=95, upload_to='static/parthers', verbose_name='image', width_field=135),
        ),
        migrations.AlterField(
            model_name='sectionsixcustomerssay',
            name='image_background',
            field=models.ImageField(upload_to='static/image', verbose_name='image background section'),
        ),
    ]
