# Generated by Django 4.1.1 on 2023-01-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_newsimage_news_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parthernsimage',
            name='parthers',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='content.partherns'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='static/image/news', verbose_name='news image'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='text_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='partherns',
            name='text_description',
            field=models.TextField(max_length=2000),
        ),
    ]
