# Generated by Django 4.1.1 on 2023-01-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_parthernsimage_parthers_alter_newsimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address_header',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='email_header',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_header',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email2'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parthernsimage',
            name='icon',
            field=models.ImageField(upload_to='static/parthers', verbose_name='image'),
        ),
    ]
