# Generated by Django 4.1.1 on 2023-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_footer_address_header_footer_email_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='logo must be width ?px and height ?px.', upload_to='static/image/logo', verbose_name='logo')),
            ],
        ),
        migrations.AlterField(
            model_name='footer',
            name='address_header',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email_header',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_header',
            field=models.CharField(max_length=400),
        ),
    ]
