# Generated by Django 4.1.1 on 2023-01-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_logo_alter_footer_address_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionthreeicon',
            name='section_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectionthree'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(help_text='logo must be width 113 px and height 41 px.', upload_to='static/image/logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sectionthreeicon',
            name='icon',
            field=models.CharField(help_text='Go to the https://fontawesome.com/search website and search for the name of the icon and put it in this field for example fa-user', max_length=200),
        ),
    ]
