# Generated by Django 4.1.1 on 2023-01-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_sectionthreeicon_section_three_alter_logo_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name_plural': '01. Header (Menu)'},
        ),
        migrations.AlterModelOptions(
            name='sectionunderslider',
            options={'verbose_name_plural': '03. Section Under Slider (Best Sulotions)'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '02. Sliders'},
        ),
        migrations.AddField(
            model_name='sectionunderslidericon',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.sectionunderslider'),
        ),
    ]
