# Generated by Django 4.1.1 on 2023-01-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_progress_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '13. Footer'},
        ),
        migrations.AlterModelOptions(
            name='newssection',
            options={'verbose_name_plural': '11. Our Latest News'},
        ),
        migrations.AlterModelOptions(
            name='numberssection',
            options={'verbose_name_plural': '05. Section Numbers'},
        ),
        migrations.AlterModelOptions(
            name='partherns',
            options={'verbose_name_plural': '12. Our Best Partherns'},
        ),
        migrations.AlterModelOptions(
            name='porfoliodetail',
            options={'verbose_name_plural': '07. Our Latest Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='porfolioitem',
            options={'verbose_name_plural': '071. Our Latest Portfolio Item'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': '07. Our Latest Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='sectionfiveourteams',
            options={'verbose_name_plural': '09. Our Team Members'},
        ),
        migrations.AlterModelOptions(
            name='sectionfourprofessional',
            options={'verbose_name_plural': '08. We Are Professional'},
        ),
        migrations.AlterModelOptions(
            name='sectionsixcustomerssay',
            options={'verbose_name_plural': '10. What Our Customers Say'},
        ),
        migrations.AlterModelOptions(
            name='sectionthree',
            options={'verbose_name_plural': '06. Section Our Best solutions'},
        ),
        migrations.AlterModelOptions(
            name='sectiontwo',
            options={'verbose_name_plural': '04. Section (We are Creative)'},
        ),
    ]
